# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/


name: backend
services:
  server:
    build:
      dockerfile: container/Dockerfile
      context: ..
    env_file:
      - ../env/dev.env
    ports:
      - 8080:8080
    depends_on:
      phoenix-db-service:
        condition: service_healthy
#    volumes:
#      - ./mirroring:/BOOT-INF/
  phoenix-db-service:
    ports:
      - 5433:5432
    image: postgres:17.2
    restart: on-failure
    user: postgres
    secrets:
      - db-password
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
#      - db-data:/var/lib/postgresql/data
    env_file:
      - ../env/db.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
#volumes:
#  db-data:
#    name: phong
secrets:
  db-password:
    file: ../env/db_password.txt

