apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix-backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/http01-ingress-path-type: ImplementationSpecific
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vdt64.duckdns.org
      secretName: duckdns-backend-cert-tls
  rules:
    - host: vdt64.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phoenix-backend-service
                port:
                  number: 8080
