management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  metrics:
#    export:
#      otlp:
#        enabled: true
#        step: 10s
#        url: ${SPRING_OTEL_EXPORT_URL:http://localhost:4318/v1/metrics}
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s

  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: ${SPRING_OTEL_EXPORT_URL:http://localhost:4318/v1/metrics}
        step: 10s
        enabled: true
    tracing:
      export:
        enabled: true
      endpoint: ${SPRING_OTEL_TRACE_URL:http://localhost:4318/v1/traces}
#    logging:
#      endpoint: ${SPRING_OTEL_LOG_URL:http://localhost:4318}
#      export:
#        enabled: true
spring:
  logging:
    config: classpath:logback-spring.xml
