logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
    org:
      flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug
      flywaydb.core.FlywayExecutor: debug
    shop.holy.v3.ecommerce:
      shared:
        config:
          openapi:
            OpenApiConfig: INFO
    root: ERROR
    sql: INFO

openapi:
  service:
    title: "KLTN Ecommerce"
    server: 'http://localhost:8080'
    version: "1.0.0"
    group: "ECOMMERCE API Holy Shop"