spring:
  flyway:
    #    enabled: true
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:/db/migration
    # Ensure Flyway only processes insert statements
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    out-of-order: false
    default-schema: public
    enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 20
        # Disable stored procedure validation
        proc:
          schema_validation: false
        default_schema: public
    hibernate:
      ddl-auto: none

