app:
  env: dev #or prod

spring:
  application:
    name: v3-ecommerce-holy-shop
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:log,security,dev,vnp,cachenone,mail}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: sched-phong
      simple:
        concurrency-limit: -1
  web:
    resources:
      cache:
        period: 0

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
phong:
  mail:
    to: ${MAIL_TO:21522458@gm.uit.edu.vn}
    enable-fallback: ${MAIL_ENABLE_FALLBACK:true}
    banner-url: ${BANNER_URL:https://res.cloudinary.com/dm45tt6nt/image/upload/v1751191772/popqmvsqxxb2sqzjskdz.png}
    scheduled:
      cron: "0/30 * * * * *"
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    account-dir: ${CLOUDINARY_ACCOUNT_DIR}
    blog-dir: ${CLOUDINARY_BLOG_DIR}
    category-dir: ${CLOUDINARY_CATEGORY_DIR}
    coupon-dir: ${CLOUDINARY_COUPON_DIR}
    product-dir: ${CLOUDINARY_PRODUCT_DIR}


server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: always
    include-path: always

same-site: ${SAME_SITE:none}
is-secure: ${IS_SECURE:false}
target-frontend: ${TARGET_FRONTEND:http://192.168.1.15:3000,http://localhost:3000}