logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug

    org:
      springframework:
        cache: debug
      flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug
      flywaydb.core.FlywayExecutor: debug
    shop.holy.v3.ecommerce:
      shared:
        config:
          openapi:
            OpenApiConfig: INFO
    root: error
    sql: INFO

openapi:
  service:
    title: "KLTN Ecommerce"
    server: 'http://localhost:8080'
    version: "1.0.0"
    group: "ecommerce-api-holy-shop"
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    url: /v3/api-docs/ecommerce-api-holy-shop
#  cache:
#    disabled: true