admin:
  existingSecret: grafana-admin-credentials

service:
  type: ClusterIP

grafana.ini:
  server:
    root_url: http://vdt64.duckdns.org/grafana/
    serve_from_sub_path: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

sidecar:
  dashboards:
    enabled: true
    folder: /var/lib/grafana/dashboards/default
    label: grafana_dashboard
    searchNamespace: ALL
