server:
  service:
    type: ClusterIP

  extraScrapeConfigs:
    - job_name: 'backend'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['phoenix-backend-service.default.svc.cluster.local:8080']
