grafana:
  enabled: true
  adminUser: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'backend'
        static_configs:
          - targets: ['phoenix-backend-service.default.svc.cluster.local:80']
