grafana:
  enabled: true
  adminUser: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false
  grafana.ini:
    server:
      root_url: http://vdt64.duckdns.org/grafana/
      serve_from_sub_path: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'backend'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['phoenix-backend-service.default.svc.cluster.local:80']
