name: Deploy Spring Boot to AKS

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_NAME }} --name ${{ secrets.CLUSTER_NAME }} --overwrite-existing

      - name: Fetch secrets from Key Vault
        run: |
          az keyvault secret show --vault-name ${{secrets.VAULT_NAME}} --name ${{secrets.SECRET_NAME}}
        id: get_secret

      # Use the secret in your manifest (can use envsubst or kustomize or sed)
      - name: Render Kubernetes manifests
        run: |
          export DB_PASSWORD="${{ steps.get_secret.outputs.value }}"
          envsubst < k8s.yaml > rendered.yaml

      - name: Deploy to AKS
        run: |
          kubectl apply -f rendered.yaml
