name: Expose Services via Ingress

on:
  workflow_run:
    workflows: ["Setup Nginx Ingress"]
    types:
      - completed
  workflow_dispatch:

jobs:
  check-ingress-controller:
    name: Check Ingress Controller Status
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_NAME }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Check Ingress Controller Pod status
      run: |
        echo "Checking ingress-nginx-controller pod status..."
        kubectl get pods -n ingress-nginx

        echo "Checking External IP..."
        IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}' || true)

        if [ -z "$IP" ]; then
          echo "❌ Ingress Controller has no External IP yet."
          kubectl get svc ingress-nginx-controller -n ingress-nginx -o wide || true
          exit 1
        fi

        echo "✅ Ingress Controller External IP: $IP"

  deploy-ingress:
    name: Deploy Ingress Resources
    runs-on: ubuntu-latest
    needs: check-ingress-controller
    environment: prod
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_NAME }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Install cert-manager
      run: |
        kubectl label namespace ingress-nginx cert-manager.io/disable-validation=true
        helm repo add jetstack https://charts.jetstack.io
        helm repo update
        helm upgrade --install cert-manager jetstack/cert-manager \
          --namespace ingress-nginx \
          --version=v1.8.0 \
          --set installCRDs=true \
          --set nodeSelector."kubernetes\.io/os"=linux

    - name: Apply ClusterIssuer (Let's Encrypt)
      run: kubectl apply -f k8s/cert-manager/cluster-issuer.yaml

    - name: Apply Ingress Resources (with TLS)
      run: |
        kubectl apply -f k8s/ingress/backend-ingress.yaml
        kubectl apply -f k8s/ingress/grafana-ingress.yaml
