name: Deploy Monitoring Stack

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    if: ${{ vars.ENV == 'prod' }}
    environment: prod

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_NAME }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}


    - name: Get email password from Azure Key Vault
      id: getsecret
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.VAULT_NAME }}
        secrets: |
          grafana-email-password

    - name: Add Helm Repos
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Create Namespace
      run: |
        kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

    - name: Install kube-prometheus-stack with custom values
      run: |
        helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
          -f k8s/helm/values.yaml \
          --set grafana.adminPassword=${{ secrets.GRAFANA_PASSWORD }} \
          --set grafana.grafana.ini.smtp.password=${{ steps.getsecret.outputs.grafana-email-password }} \
          --namespace monitoring
