name: Setup Nginx Ingress

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    if: ${{ vars.ENV == 'prod' }}
    environment: prod

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_NAME }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}

    - name: Add ingress-nginx repo
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

    - name: Deploy ingress-nginx
      run: |
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --version 4.7.1 \
          --namespace ingress-nginx \
          --create-namespace \
          --set controller.replicaCount=2 \
          --set controller.nodeSelector."kubernetes\.io/os"=linux \
          --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
          --set controller.service.externalTrafficPolicy=Local \
          --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux \
          --set controller.service.loadBalancerIP=57.155.62.73 \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=${{ secrets.RESOURCE_NAME }}
      
    - name: Verify deployment
      run: |
        kubectl get pods -n ingress-nginx
        kubectl get svc -n ingress-nginx
  